name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      
      - name: lock package version
        run: pipenv lock
      
      - name: install packages
        run: pipenv sync --dev
      
      - name: run test
        run: |
          pipenv run test